services:
    book1:
        image: 1190782/lmsbooks:${IMAGE_TAG}
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance1,bootstrap,test
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"
        deploy:

    book2:
        image: 1190782/lmsbooks:${IMAGE_TAG}
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance2,bootstrap,test
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"
        deploy:

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2:
