pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {

        //MAVEN_HOME = '/opt/homebrew' // (MacOS)
        MAVEN_HOME = '\\usr\\bin\\mvn' // (Ubuntu)
        // Update PATH to include Maven's bin directory
        PATH = "${env.PATH}:${MAVEN_HOME}"

        GIT_REPO_URL = 'https://github.com/1190782/odsoft-project-1190782-1230183-1230164.git'  // Your Git repository URL
        GIT_BRANCH = 'main'  // Specify the branch to check out

        SERVER_PORT = '2226'

        IMAGE_NAME = 'lmsbooks'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Debug Environment') {
            steps {
                bat 'java --version'
                bat 'mvn --version'
                bat 'dir'
                bat 'docker ps'
            }
        }

        stage('Check Docker') {
            steps {
                bat 'docker --version'
            }
        }

        stage('Checkout') {
            steps {
                // Step to clone the Git repository
                git branch: "${GIT_BRANCH}",
                    url: "${GIT_REPO_URL}"
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('project2\\lms-bookss') {
                    echo 'Installing dependencies...'
                    bat 'mvn dependency:resolve'
                }
            }
        }

        stage('Clean') {
            steps {
                dir('project2\\lms-bookss') {
                    bat 'dir'
                    bat 'mvn clean compile'
                }
                
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('project2\\lms-bookss') {
                    bat 'docker build -f DockerfileWithPackaging -t lmsbooks .'
                }
            }
        }

        stage("Send Email for Approval"){
          steps{
                script{
                    echo "Sending email"
                    try {
                        emailext attachLog: true, body: 'The pipeline already run. It is necessary your approval. Please check the pipeline.', subject: 'Pipeline Ready to Approve', to: 'engreq950@gmail.com'
                    } finally {
                        echo "Email sent"
                        input "Do you want to continue?"
                    }
                }
          }
    }

        stage('Deploy with Docker Compose') {
            steps {
                script {
                    bat """

                        if ! docker ps --filter "name=rabbitmq_in_lms_network" --format '{{.Names}}' | grep -q rabbitmq_in_lms_network; then
                          docker compose -f docker-compose-rabbitmq.yml up -d
                        else
                          echo "RabbitMQ container already running."
                        fi

                        if ! docker ps --filter "name=postgres_in_lms_network" --format '{{.Names}}' | grep -q postgres_in_lms_network; then
                          docker compose -f docker-compose-postgres.yml up -d
                        else
                          echo "Postgres container already running."
                        fi


                        docker compose -f docker-compose.yml up -d --force-recreate

                    """
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed. Cleaning workspace...'
            //cleanWs()
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }

}