pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK 21'
    }

    environment {
        MAVEN_HOME = '\\usr\\bin\\mvn'
        PATH = "${env.PATH}:${MAVEN_HOME}"
        GIT_REPO_URL = 'https://github.com/1190782/odsoft-project-1190782-1230183-1230164.git'
        GIT_BRANCH = 'main'
        SERVER_PORT = '2226'
        IMAGE_NAME = 'lmsusers'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Debug Environment') {
            steps {
                bat 'java --version'
                bat 'mvn --version'
                bat 'dir'
                bat 'docker ps'
            }
        }

        stage('Check Docker') {
            steps {
                bat 'docker --version'
            }
        }

        stage('Checkout') {
            steps {
                git branch: "${GIT_BRANCH}",
                    url: "${GIT_REPO_URL}"
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('project2\\lms-bookss') {
                    echo 'Installing dependencies...'
                    bat 'mvn dependency:resolve'
                }
            }
        }

        stage('Build') {
            steps {
                dir('project2\\lms-userss') {
                    bat 'dir'
                    bat 'mvn clean compile'
                }

            }
        }

        stage('Docker Build') {
            steps {
                dir('project2\\lms-userss') {
                    bat 'mvn package'
                    bat 'docker build -t 1190782/lmsusers:latest .'
                }
            }
        }

        stage('Docker Image Push Repository') {
            steps {
                dir('project2\\lms-userss') {
                    bat 'docker login -u 1190782 -p dckr_pat_78I6z_Ldwkw1VgXleBe7Oa6F3f0'
                    bat 'docker push 1190782/lmsusers:latest'
                    bat 'docker logout'
                }
            }
        }

         stage('Checkstyle') {
            steps {
                dir('project2\\lms-userss') {
                    script {
                        bat 'mvn checkstyle:checkstyle -Dcheckstyle.failOnViolation=false'
                    }
                }
            }
         }

         stage('Publish Checkstyle Report') {
             steps {
                dir('project2\\lms-userss') {
                     publishHTML([
                         reportDir: 'target/site',
                         reportFiles: 'checkstyle.html',
                         reportName: 'Checkstyle Report',
                         keepAll: true,
                         allowMissing: false,
                         alwaysLinkToLastBuild: true
                     ])
                }
             }
         }

         stage('Tests') {
              steps {
                  dir('project2\\lms-userss') {
                      script {
                            bat 'mvn test'
                      }
                  }
              }
         }

         stage('Jacoco') {
             steps {
                 dir('project2\\lms-userss') {
                     jacoco execPattern: '**/target/jacoco.exec',
                            classPattern: '**/target/classes',
                            sourcePattern: '**/src/main/java',
                            inclusionPattern: '**/*.class'
                 }
             }
         }

         stage('Publish JaCoCo Report') {
             steps {
                 dir('project2\\lms-userss') {
                     publishHTML([
                         reportDir: 'target/site/jacoco',
                         reportFiles: 'index.html',
                         reportName: 'JaCoCo Report',
                         keepAll: true,
                         allowMissing: false,
                         alwaysLinkToLastBuild: true
                     ])
                 }
             }
         }
    }

    post {
        always {
            echo 'Pipeline completed. Cleaning workspace...'
            cleanWs()
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}